version: 2.1
executors:
  js-env:
    docker:
      - image: circleci/node:11.4

jobs:
  js-test:
    executor: js-env
    working_directory: ~/app
    steps:
      - checkout
      - run: npm ci
      - run: npm run test

workflows:
  version: 2.1
  js:
    jobs:
      - js-test:
          filters:
            branches:
              only: /^js-.*$/
